### ISSUE TITLE
Admin Media query "404 error: Unrecognized request"

### ISSUE THREAD

**Issue by TafkaMax** [realtyem/synapse-workers#9]
I have noticed an interesting issue with the Media query. When I am using the admin API, with synapse-admin UI I can't see users media. https://element-hq.github.io/synapse/v1.105/admin_api/user_admin_api.html#list-media-uploaded-by-a-user

When digging a little deeper into the logs I get this.

```
synapse_main | 2024-04-24 06:55:41,649 - synapse.http.server - 130 - INFO - GET-6677 - <XForwardedForRequest at 0x7fb513333f50 method='GET' uri='/_synapse/admin/v1/users/%40REDACTED%3Aexample.com/media?dir=b&from=0&limit=50&order_by=created_ts' clientproto='HTTP/1.1' site='8080'> SynapseError: 404 - Unrecognized request
```

The API call via CLI is this:

```bash
curl -X GET -H 'Content-Type: application/json' https://home-server.example.com/_synapse/admin/v1/users/@REDACTED:example.com/media\&access_token=TOKEN | jq
```

```json
{
  "errcode": "M_UNRECOGNIZED",
  "error": "Unrecognized request"
}
```

When running the upstream "simple" image I do not have this issue.

These are the workers I have enabled.
```
SYNAPSE_WORKER_TYPES=appservice, background_worker, client_reader:3, event_creator, event_persister:3, frontend_proxy, media_repository, pusher, presence, receipts, synchrotron:3, typing, user_dir, stream_writers=account_data+to_device
```

**Comment by realtyem** [comment]
Interesting find. Looking into this, I found that the place it is defined is unchanged from the upstream original script that the configuration generation is based on. The docs say `users` and the original script says `user`. Makes me wonder if they are actually testing this stuff. Should be a fairly easy fix. In the mean time, if you wish, you can `exec -it` into the image with `/bin/bash` and `nano /etc/nginx/conf.d/matrix-synapse.conf` to edit it by hand, then restart.

Look for the `proxy_pass http://media_repository.media;` with the `/_synapse/admin/v1/user/.*/media.*$` and just add an `s`. If this works for you, give me a shout and I'll definitely fix it(and send it upstream too).

**Comment by TafkaMax** [comment]
Yup editing it the nginx conf inside the container fixed the API call!

**Comment by realtyem** [comment]
Sorry this took a minute, I got backed up on something else. I'm glad it ended up working.

I took a few minutes to dig into this and it turns out there actually are two endpoints, a `/user` and a `/users` so I just added the one instead of replacing it.

Fixed in [cb24387](https://github.com/realtyem/synapse-workers/commit/cb24387cbef01dcd1b790f4e1502ddff66190d89)

**Comment by realtyem** [comment]
If it does end up working correctly after wards, drop me a note or go ahead and close this(in case something else comes up)

**Comment by TafkaMax** [comment]
Works :)
